---
- name: hostname | hostname updated (pt. 1) - hostname cmd
  hostname:
    name: "{{ hostname }}"
  become: True

- name: hostname | hostname updated (pt. 2) - (/etc/hostname)
  copy:
    content: "{{ hostname }}{{ '\n' }}"
    dest: "/etc/hostname"
    owner: root
    group: root
    mode: 0644
  become: True

- name: hostname | IPv4 hostname updated (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: "/etc/hosts"
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{ '\t' }}{{ hostname }}{{ '\t' }}localhost"
    state: present
  become: True

- name: hostname | IPv6 hostname updated (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: "/etc/hosts"
    regexp: "^::1"
    line: "::1{{ '\t\t' }}{{ hostname }}{{ '\t' }}localhost ip6-localhost ip6-loopback"
    state: present
  become: True
