---
- name: "Create Ruby 2.2 installation dir"
  file:
    state: directory
    path: /tmp/ruby2.2

- name: "Unarchive Ruby 2.2"
  unarchive:
    src: https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.6.tar.bz2
    dest: /tmp/
    remote_src: True
    creates: /tmp/ruby-2.2.6

- name: Install Ruby 2.2 from source
  shell: ./configure && make && make install
  args:
    chdir: /tmp/ruby-2.2.6
    creates: "/usr/local/include/ruby-2.2.0"

- name: base gems installed
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: False
    state: present
  become: True
  with_items:
    - { name: "rack", version: "1.6.0" }
    - { name: "unicorn", version: "4.8.3" }
    - { name: "shotgun", version: "0.9" }
